import Validator from 'protoflow-validator';
import { useApp } from './http/app';
import { useMiddleware } from './http/context';
import { useQuery } from './http/mango/model';
import { useRouter } from './http/router';
import { useModules } from './kernel/autoload';
import { useModel } from './kernel/model';
import { useMongoDB } from './kernel/mongodb';
declare const useValidator: () => Validator;
declare const useMangoQueryParser: () => <T extends import("./kernel/mql").OutputTarget>(target: T, context?: Partial<import("./kernel/mql").Context>) => (query: string) => (T extends "json" ? string : never) | (T extends "json" ? never : import("./kernel/mql").ParsedObject);
export { useApp, useMangoQueryParser, useMiddleware, useModel, useModules, useMongoDB, useQuery, useRouter, useValidator };
