"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const protoflow_validator_1 = __importDefault(require("protoflow-validator"));
const app_1 = require("./http/app");
exports.useApp = app_1.useApp;
const context_1 = require("./http/context");
exports.useMiddleware = context_1.useMiddleware;
const microservice_1 = require("./http/microservice");
exports.describeMicroService = microservice_1.describeMicroService;
exports.useMicroService = microservice_1.useMicroService;
const router_1 = require("./http/router");
exports.useRouter = router_1.useRouter;
const autoload_1 = require("./kernel/autoload");
exports.requireModules = autoload_1.requireModules;
const model_1 = require("./kernel/magy/model");
exports.useQuery = model_1.useQuery;
const query_1 = require("./kernel/magy/query");
exports.resolveQuery = query_1.resolveQuery;
const model_2 = require("./kernel/model");
exports.disableModelSync = model_2.disableModelSync;
exports.enableModelSync = model_2.enableModelSync;
exports.useModel = model_2.useModel;
const mongodb_1 = require("./kernel/mongodb");
exports.useMongoDB = mongodb_1.useMongoDB;
const useValidator = () => new protoflow_validator_1.default;
exports.useValidator = useValidator;
