"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const protoflow_validator_1 = __importDefault(require("protoflow-validator"));
const app_1 = require("./http/app");
exports.useApp = app_1.useApp;
const context_1 = require("./http/context");
exports.useMiddleware = context_1.useMiddleware;
const model_1 = require("./http/mango/model");
exports.useQuery = model_1.useQuery;
const router_1 = require("./http/router");
exports.useRouter = router_1.useRouter;
const autoload_1 = require("./kernel/autoload");
exports.useModules = autoload_1.useModules;
const microservice_1 = require("./kernel/microservice");
exports.registerMicroServiceFunc = microservice_1.registerMicroServiceFunc;
exports.useMicroService = microservice_1.useMicroService;
const model_2 = require("./kernel/model");
exports.useModel = model_2.useModel;
const mongodb_1 = require("./kernel/mongodb");
exports.useMongoDB = mongodb_1.useMongoDB;
const useValidator = () => new protoflow_validator_1.default;
exports.useValidator = useValidator;
